var triggerlist = [
"What do you need to start?",
"What do you need to finish?",
"What needs clarification?",
"Have you defined next actions for all projects?",
"Anything outstanding in your notepad?",
"Anything outstanding in your calendar?",
"Anything outstanding in your journal?",
"Anything outstanding In your planner?",
"Anything outstanding in to do lists?",
"Any loose post it notes?",
"Any phone messages?",
"Any phone texts?",
"Anything lingering in your inbox?",
"Remember anything from any meetings this week?",
"What discussions do you need to follow up on?",
"What's your boss waiting on?",
"Are your partners/collegues waiting on anything from you?",
"Do your subordinates need anything from you to continue their work?",
"What are your customers/clients expecting?",
"Do you need to do anything with/for your doctor?",
"Do you need to do anything with/for your lawyer?",
"Do you need to call the dentist?",
"Do you need to do communicate with your accountant for anything?",
"What does your spouse need from you this week?",
"What do you need to do for your kids?",
"Do you have any responsibilities regarding your pets?",
"Do you need to do anything for your parents/family?",
"What friends do you need to contact/assist?",
"Do you need to do something for your neighborhood this week?",
"Have you borrowed anything that need returning?",
"Do you need to deliver anything?",
"Have you made all the payments you need to make?",
"What deadlines are coming up?",
"Do you need to make/receive any phone calls?",
"Do you need to have any important or urgent conversations?",
"Have you responded to all your voicemails?",
"Have you left any voicemail that needs a response?",
"Do you have any texts that you need to send/receive/respond to?",
"Are you waiting on any faxes, or do you need to send any?",
"Do you have any letters to read/write?",
"Do you have any important emails to write or to follow up on?",
"Do you need to send any birthday/anniversary/other cards?",
"Is anyone waiting on your RSVP?",
"Do you have actionable facebook/twitter/website notifications?",
"Do you need to check your internet forums?",
"Do you need anything from the hardware store?",
"Need anything from the pharmacy?",
"Do you need to go to the grocery store?",
"Do you need anything from the mall?",
"Need to make a run to the post office?",
"Do you need to drop off or pick up at the dry cleaners?",
"Do you need office supplies / stationary?",
"Does your car need gas?",
"Do you have to get any gifts or presents?",
"Need any pet supplies?",
"Do you have any repairs to get done?",
"Do you have to go to the bank?",
"Do you have any bills to pay?",
"Do you need cash?",
"Do you need to update your budget",
"Do you need to fill out/deliver any forms?",
"Do you need to do any online banking?",
"Do you have loans to pay off?",
"How are your investments? Anything you need to check on?",
"Do you have taxes to pay?",
"Have you filed your taxes?",
"Do you need to update your insurance info?",
"Do you need to pay your insurance bill?",
"Do you need to get legal advice?",
"Do you need to update your will?",
"Do you have personnel issues to manage?",
"Do you have policy to enforce/update?",
"Do you need to resupply?",
"Do you need to develop/publish/train new procedures?",
"Do you need to get medical advice?",
"Do you need to get or learn to use new equipment?",
"Do you have equipment to maintain?",
"Do you need to do any estate planning?",
"Have you got any public relations issues to attend to?",
"Are waiting on any communications?",
"Are you waiting on any orders?",
"Do you have any repairs you need to check on?",
"Are you waiting on any loaned items?",
"Are you expecting some data or information from someone?",
"Are you expecting a delivery?",
"Did you delegate any tasks that you need to check in on?",
"Are you waiting for tickets for an event?",
"Do you need someone else to make a decision?",
"Arey you waiting on a proposal?",
"Do you need to get reimbursed for something?",
"Do you have a subscription you need to get/cancel?",
"Are you waiting for a special reply?",
"What events are upcoming?",
"Do you need to RSVP/confirm attendance at an event?",
"Do you need to cancel a reservation or event?",
"Do you need to plan an event?",
"Any upcoming meetings?",
"Any upcoming special occasions?",
"Any upcoming birthdays?",
"Any upcoming anniversaries?",
"Any upcoming weddings?",
"Any upcoming graduations?",
"Any upcoming holidays?",
"Any upcoming travel?",
"Any upcoming vacations?",
"Any upcoming social events?",
"Any upcoming sporting events?",
"Any upcoming seminars/conferences?",
"Does anything need to be repaired?",
"What needs to be replaced?",
"Is it time for a software update?",
"Do you need to upgrade any computer hardware?",
"Do you need to download anything?",
"Do you need printer ink or paper?",
"Do you need to upgrade or repair any appliances or equipment?",
"Do you need any tools?",
"What goals are outstanding?",
"What targets need to be met?",
"Do you have any objectives that need to be met?",
"What projects need to be reviewed?",
"Do you need to do any planning?",
"Do you have any marketing to do?",
"What new initiatives need to be worked out?",
"Can you think of any upcoming events?",
"Any meetings you need to prep for?",
"Do you have a presentation coming up?",
"How's your security?",
"Do you need to plan any travel?",
"Do you need to work out any transportation plans?",
"Do you have subscriptions to make or cancel?",
"Do you need to set aside time to do some career planning?",
"Any educational concerns?",
"Do you have any schedules to develop or review?",
"Do you need to give or receive feedback on anything?",
"Do you need to hire (or fire) anyone for anything?",
"Does any sorting need to be done?",
"Do you need to organize anything?",
"What needs to be posted?",
"What needs to be reviewed?",
"What do you need to read?",
"What do you need to watch?",
"What do you need to listen to?",
"What do you need to write?",
"What do you need to record?",
"Any books/magazines/newspapers you need to read?",
"Any documents you need to review?",
"What websites do you need to check?",
"Do you have any subscriptions you need to read?",
"Do you have emails you need to read?",
"Do you have letters you need to read?",
"Do you need to read any reports?",
"Do you need to review any manuals or instructions?",
"Do you need to see any TV shows?",
"Do you need to watch any videos?",
"Do you have a radio show or podcast you need to listen to?",
"Is it laundry time?",
"Do you need to go to the dry cleaners to drop off or pick up?",
"Do you need to purge and donate some clothes?",
"Do you need to get clothes for work, sports, or leisure?",
"Do you need to store or unpack some seasonal clothes?",
"Do you have clothes that don't fit that you can get rid of?",
"Do you need a haircut?",
"Do you need to make a dental appointment?",
"Do you need to make a doctors appointment?"
]